---
http:
  # SSL configuration
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

  # Enables additional IP filtering.
  ip_ban_enabled: true

  # Number of failed login attempts from a single IP after which it will
  # be automatically banned.
  login_attempts_threshold: 5
