---
id: office_auto_climate
alias: 'Office auto climate'
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.vacation
      state: 'off'
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - 'armed_home'
        - 'disarmed'
    - condition: state
      entity_id: input_boolean.auto_heating
      state: 'on'
    - condition: state
      entity_id: group.office_lights
      state: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.office_thermostat
      temperature: 30
      hvac_mode: heat
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.office_motion
        from: 'on'
        to: 'off'
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.office_thermostat
      hvac_mode: 'off'
mode: restart
