---
id: desk_leds_on
alias: 'Turn ON desk leds'
hide_entity: true
trigger:
  - platform: state
    entity_id: switch.fibaro_office_switch_2
    to: 'on'
action:
  - service: light.turn_on
    entity_id:
      - light.office_desk_leds
