---
id: desk_leds_off
alias: 'Turn OFF desk leds'
hide_entity: true
trigger:
  - platform: state
    entity_id: light.office_desk_light
    to: 'off'
  - platform: state
    entity_id: switch.fibaro_office_switch_2
    to: 'off'
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: light.office_desk_light
            state: 'off'
          - condition: state
            entity_id: switch.fibaro_office_switch_2
            state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: light.office_desk_light
            state: 'on'
          - condition: state
            entity_id: switch.fibaro_office_switch_2
            state: 'off'
action:
  - service: light.turn_off
    entity_id:
      - light.office_desk_color_light
