---
id: motion_detected_office_presence
alias: Motion Detected In The Office Presence
trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_office
    to: 'on'
condition:
  condition: state
  entity_id: person.pablo
  state: 'home'
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.office_desk_light
        - light.office_desk_color_light
        - light.office
      transition: 3
