---
id: motion_cleared_office
alias: Motion Cleared In The Office Presence
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion
    to: 'off'
    for:
      minutes: 5
condition:
  condition: state
  entity_id: person.pablo
  state: 'home'
action:
  - service: light.turn_off
    entity_id:
      - light.office_desk_light
      - light.office_desk_color_light
      - light.office
