---
id: turn_off_ac_when_away_or_bedtime
alias: Turn off AC when away or bed time
trigger:
  - platform: state
    entity_id: input_boolean.away
    to: 'on'
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
condition:
  condition: template
  value_template: "{{ not is_state('climate.office_thermostat', 'off') }}"
action:
  - service: climate.set_operation_mode
    data:
      entity_id: climate.office_thermostat
      operation_mode: 'off'
