---
id: turn_off_ac_when_away
alias: Turn off AC when away
trigger:
  - platform: state
    entity_id: input_boolean.away
    to: 'on'
condition:
  condition: template
  value_template: "{{ not is_state('climate.office_thermostat', 'off') }}"
action:
  - service: climate.set_operation_mode
    data:
      entity_id: climate.office_thermostat
      operation_mode: 'off'
