---
id: turn_off_ac_when_away_or_bedtime
alias: Turn off AC when away or bed time
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
  - platform: state
    entity_id: binary_sensor.office_motion
    to: 'off'
    for:
      minutes: 20
condition:
  condition: template
  value_template: "{{ not is_state('climate.office_thermostat', 'off') }}"
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.office_thermostat
      hvac_mode: 'off'
