---
id: turn_off_office_lights_when_away
alias: Turn off ofice lights when away
trigger:
  - platform: state
    entity_id: input_boolean.away
    to: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: group.office_lights
