---
id: turn_off_office_lights_when_away
alias: Turn off ofice lights when away
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    from: 'disarmed'
    to: 'armed_away'
action:
  - service: homeassistant.turn_off
    entity_id: group.office_lights
