---
id: enable_movies
alias: Enable Movies Mode
trigger:
  - platform: state
    entity_id: input_boolean.movies
    to: 'on'
action:
  - service: scene.create
    data:
      scene_id: movies_before
      snapshot_entities:
        - light.dining_room_1
        - light.dining_room_2
        - light.living_room
        - light.living_lamp
  - service: scene.turn_on
    data:
      entity_id: scene.movies
