---
id: stairs_window_1_open
alias: Stairs Window 1 Opened
trigger:
  - platform: state
    entity_id: binary_sensor.stair_window_1
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'on'
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Security - Stair window 1'
      message: 'The stairs window 1 was opened'
      data:
        push:
          sound:
            name: US-EN-Daisy-Office-Window-Open.wav
            critical: 1
            volume: 1.0
  - service: homeassistant.turn_on
    entity_id: group.inside_lights
