---
image: docker:latest

stages:
  - preflight
  - homeassistant

yamllint:
  image: sdesbure/yamllint
  stage: preflight
  tags:
    - docker
  before_script:
    - yamllint --version
  script:
    - yamllint .

homeassistant:
  image:
    name: homeassistant/home-assistant:latest
    entrypoint: [""]
  stage: homeassistant
  tags:
    - docker
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - python -m homeassistant --version
    - cp -R ./.stub/ssl /
    - cp -R ./.stub/android /config/
    - cp ./.stub/secrets.yaml ./config/
    - wget https://github.com/mool/home-assistant-bgh-smart/archive/master.zip
    - unzip master.zip
    - mv home-assistant-bgh-smart-master/custom_components/bgh_smart ./config/custom_components/
  script:
    - |
      python -m homeassistant \
        --config ./config/ \
        --script check_config \
        --info all
