---
platform: generic
name: Espora East
still_image_url: http://10.1.80.98:8000/cgi-bin/snapshot.cgi?channel=2
stream_source: !secret camera_dorrego_url_2
username: !secret camera_dorrego_username
password: !secret camera_dorrego_password
