---
id: roof_camera_battery
alias: 'Roof camera battery'
trigger:
  - platform: numeric_state
    entity_id: sensor.techo_comedor_battery
    below: 25
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.techo_comedor_battery
    below: 10
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.techo_comedor_battery
    below: 5
    for:
      minutes: 5
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Battery - Roof camera'
      message: "The roof camera is at {{ states('sensor.techo_comedor_battery') }}% battery"
