---
id: motion_detected_roof
alias: Motion Detected In The Roof
trigger:
  - platform: state
    entity_id: binary_sensor.ring_techo_comedor_motion
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'on'
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Security - Roof'
      message: 'Motion detected in the Roof'
      data:
        push:
          sound:
            name: US-EN-Morgan-Freeman-Motion-Detected.wav
            critical: 1
            volume: 1.0
  - service: homeassistant.turn_on
    entity_id: group.inside_lights
