---
id: motion_detected_roof
alias: Motion Detected In The Roof
trigger:
  - platform: state
    entity_id: binary_sensor.ring_techo_comedor_motion
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'on'
action:
  - service: notify.html5
    data:
      title: 'Security - Roof'
      message: 'Motion detected in the Roof'
  - service: homeassistant.turn_on
    entity_id: group.inside_lights
