---
id: ac_off_workday
alias: 'Turn OFF the AC on workdays'
trigger:
  - platform: time
    at: '09:30:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: climate.comedor
      state: heat
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.comedor
      hvac_mode: 'off'
