---
id: ac_on_workday
alias: 'Turn ON the AC on workdays'
trigger:
  - platform: time
    at: '08:50:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.comedor
      temperature: 28
      operation_mode: heat
