---
id: turn_off_dining_room_ac_when_away
alias: Turn off the Dining Room AC when away
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
condition:
  condition: template
  value_template: "{{ not is_state('climate.comedor', 'off') }}"
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.comedor
      hvac_mode: 'off'
