---
platform: unifi
host: !secret unifi_host
username: !secret unifi_username
password: !secret unifi_password
verify_ssl: false
ssid_filter:
  - moolandia-hq
new_device_defaults:
  track_new_devices: false
  hide_if_away: false
