---
id: exterior_lights_off
alias: 'Exterior lights OFF at sunrise'
trigger:
  - platform: sun
    event: sunrise
    offset: '00:30:00'
action:
  - service: switch.turn_off
    entity_id:
      - switch.backyard_light
      - switch.fibaro_office_switch
      - switch.enerwave_living_switch_2
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Exterior lights'
      message: 'The exterior lights are OFF'
