---
id: exterior_lights_off
alias: 'Exterior lights OFF at sunrise'
hide_entity: true
trigger:
  - platform: sun
    event: sunrise
    offset: '01:00:00'
action:
  - service: switch.turn_off
    entity_id:
      - switch.fibaro_office_switch
      - switch.enerwave_living_switch_2
  - service: notify.html5
    data:
      title: 'Exterior lights'
      message: 'The exterior lights are OFF'
