---
id: exterior_lights_on
alias: 'Exterior lights ON at sunset'
hide_entity: true
trigger:
  - platform: sun
    event: sunset
    offset: '-00:05:00'
action:
  - service: switch.turn_on
    entity_id:
      - switch.fibaro_office_switch
      - switch.enerwave_living_switch_2
  - service: notify.html5
    data:
      title: 'Exterior lights'
      message: 'The exterior lights are ON'
