---
id: exterior_lights_on
alias: 'Exterior lights ON at sunset'
trigger:
  - platform: sun
    event: sunset
    offset: '-00:05:00'
action:
  - service: homeassistant.turn_on
    entity_id: group.outside_lights
  - service: light.turn_on
    entity_id:
      - light.backyard
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Exterior lights'
      message: 'The exterior lights are ON'
