---
id: interior_lights_off_on_bedtime
alias: 'Interior lights OFF on bedtime'
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    from: 'disarmed'
    to: 'armed_home'
action:
  - service: homeassistant.turn_off
    entity_id: group.inside_lights
