---
id: interior_lights_off_on_vacation
alias: 'Interior lights OFF on vacation'
trigger:
  platform: time
  at: '01:00:00'
condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: group.inside_lights
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Interior lights'
      message: 'Turning OFF the interior lights - Vacation mode'
