---
id: interior_lights_on
alias: 'Interior lights ON before sunset'
trigger:
  - platform: sun
    event: sunset
    offset: '-00:45:00'
  - platform: numeric_state
    entity_id: sensor.dining_room_illumination
    below: 700
condition:
  condition: and
  conditions:
    - condition: time
      before: '21:00:00'
      after: '14:00:00'
    - condition: state
      entity_id:
        - switch.enerwave_living_switch_1
        - switch.fibaro_kitchen_switch_2
        - switch.fibaro_dining_room_switch_1
      state: 'off'
action:
  - service: switch.turn_on
    entity_id:
      - switch.enerwave_living_switch_1
      - switch.fibaro_kitchen_switch_2
      - switch.fibaro_dining_room_switch_1
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Interior lights'
      message: 'Turning ON the lights of the kitchen, living and dining room'
