---
name: Movies
entities:
  light.dinning_room_1:
    state: 'off'
  light.dinning_room_2:
    state: 'off'
  light.living_lamp:
    state: 'on'
    transition: 5
    brightness_pct: 60
  light.living_room:
    state: 'off'
