---
alarm_away_sensors:
  name: alarm_away_sensors
  entities:
    - binary_sensor.motion_sensor_office
    - binary_sensor.balcon_oficina_motion
    - binary_sensor.comedor_motion
    - binary_sensor.jardin_trasero_motion
    - binary_sensor.techo_comedor_motion
    - binary_sensor.stair_window_1
    - binary_sensor.stair_window_2
