---
alarm_home_sensors:
  name: alarm_home_sensors
  entities:
    - binary_sensor.balcon_oficina_motion
    - binary_sensor.jardin_trasero_motion
    - binary_sensor.techo_comedor_motion
    - binary_sensor.stair_window_1
    - binary_sensor.stair_window_2
