---
inside_lights:
  name: Inside Lights
  icon: mdi:lightbulb
  entities:
    - light.dinning_room
    - light.kitchen
    - light.living_lamp
    - light.living_room
    - light.office
    - light.office_desk_light
    - light.office_desk_color_light
