---
interior_lights:
  name: Interior Lights
  icon: mdi:lightbulb
  entities:
    - light.backyard
    - light.bathroom
    - light.bedroom_lamp
    - light.dining_room_1
    - light.dining_room_2
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_leds
    - light.living_lamp
    - light.living_room
    - light.office
    - light.office_desk_color_light
    - light.office_desk_light
