---
id: bedroom_outlet_off_workdays
alias: 'Turn OFF the bedroom power outlet on workdays'
trigger:
  - platform: time
    at: '02:30:00'
  - platform: time
    at: '09:15:00'
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
action:
  - service: switch.turn_off
    entity_id: switch.bedroom_outlet
