---
id: bedroom_outlet_on_workday
alias: 'Turn ON the bedroom power outlet on workdays'
hide_entity: true
trigger:
  - platform: time
    at: '23:30:00'
  - platform: time
    at: '07:30:00'
condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: "on"
action:
  - service: switch.turn_on
    entity_id: switch.bedroom_outlet
