---
id: bedroom_outlet_on_weekends
alias: 'Turn ON the bedroom power outlet on weekends'
hide_entity: true
trigger:
  - platform: time
    at: '23:30:00'
  - platform: time
    at: '09:30:00'
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "off"
action:
  - service: switch.turn_on
    entity_id: switch.bedroom_outlet
