---
id: toggle_bed_lamp
alias: Toggle Bed Lamp
trigger:
  - device_id: 6ca70a5a3d435609413cf57bd7e87be5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
action:
  - service: light.toggle
    data:
      entity_id: light.bedroom_lamp
