---
id: toggle_bed_lamp
alias: Toggle Bed Lamp
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.bedroom_switch
      click_type: single
action:
  - service: light.toggle
    data:
      entity_id: light.bedroom_lamp
