---
id: disable_away
alias: Disable Away
trigger:
  - platform: state
    entity_id: person.pablo
    to: home
  - platform: state
    entity_id: person.dad
    to: home
  - platform: state
    entity_id: person.mom
    to: home
  - platform: state
    entity_id: person.vanesa
    to: home
condition:
  condition: state
  entity_id: input_boolean.away
  state: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.away
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.home_alarm
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'Away Mode'
      message: 'The away mode is OFF'
