---
id: enable_away
alias: Enable Away
trigger:
  - platform: state
    entity_id: person.pablo
    to: not_home
  - platform: state
    entity_id: person.dad
    to: not_home
  - platform: state
    entity_id: person.mom
    to: not_home
  - platform: state
    entity_id: person.housemaid
    to: not_home
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: person.pablo
      state: not_home
    - condition: state
      entity_id: person.dad
      state: not_home
    - condition: state
      entity_id: person.mom
      state: not_home
    - condition: state
      entity_id: person.housemaid
      state: not_home
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.away
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.home_alarm
