---
platform: template
sensors:
  office_door_battery:
    friendly_name: "Office Door Battery"
    unit_of_measurement: '%'
    value_template: "{{ state_attr('binary_sensor.office_door', 'battery_level') | round(0) }}"
    device_class: "battery"
