---
platform: template
sensors:
  office_motion_battery:
    friendly_name: "Office Motion Battery"
    unit_of_measurement: '%'
    value_template: "{{ state_attr('binary_sensor.motion_sensor_office', 'battery_level') | round(0) }}"
    device_class: "battery"
