---
platform: template
sensors:
  stair_window_2_battery:
    friendly_name: "Stair Window 2 Battery"
    unit_of_measurement: '%'
    value_template: "{{ state_attr('binary_sensor.stair_window_2', 'battery_level') | round(0) }}"
    device_class: "battery"
