---
title: Backyard
path: backyard
icon: mdi:flower
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        template: edge
      - type: custom:button-card
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace-minimalist/main
      - type: custom:button-card
        template: edge
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Lights
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light
            entity: light.backyard
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Garden Irrigation
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_input_boolean
            entity: input_boolean.garden_irrigation
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_script
            variables:
              ulm_card_script_title: Trigger irrigation
              ulm_card_script_icon: mdi:water-pump
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.garden_irrigation
          - type: custom:button-card
            template: card_power_outlet
            entity: switch.garden_irrigation
      - type: entities
        show_header_toggle: false
        entities:
          - input_number.garden_irrigation_duration
          - timer.garden_irrigation_duration
          - sensor.last_irrigated_time
