---
title: Bedroom
path: bedroom
icon: mdi:bed
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        template: edge
      - type: custom:button-card
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace-minimalist/main
      - type: custom:button-card
        template: chip_icon_state
        variables:
          ulm_chip_icon_state_icon: '🌡️'
          ulm_chip_icon_state_entity: sensor.esphome_bedroom_temperature
      - type: custom:button-card
        template: chip_icon_state
        variables:
          ulm_chip_icon_state_icon: '💧'
          ulm_chip_icon_state_entity: sensor.esphome_bedroom_humidity
      - type: custom:button-card
        template: edge
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Lights
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light
            entity: light.bedroom_lamp
          - type: custom:button-card
            template: card_power_outlet
            entity: switch.bedroom_outlet
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Media
          - type: custom:button-card
            template: edge
      - type: custom:button-card
        template: card_media_player_with_controls
        variables:
          ulm_card_media_player_with_controls_name: Fire TV
          ulm_card_media_player_with_controls_entity: media_player.firetv_bedroom
