---
title: Kitchen
path: kitchen
icon: mdi:chef-hat
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        template: edge
      - type: custom:button-card
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace-minimalist/main
      - type: custom:button-card
        template: edge
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Lights
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light
            entity: light.kitchen_1
          - type: custom:button-card
            template: card_light
            entity: light.kitchen_2
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light_slider_collapse
            entity: light.kitchen_leds
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Media
          - type: custom:button-card
            template: edge
      - type: custom:button-card
        template: card_media_player_with_controls
        variables:
          ulm_card_media_player_with_controls_name: Sonos Kitchen
          ulm_card_media_player_with_controls_entity: media_player.cocina
