---
title: Living Room
path: living_room
icon: mdi:sofa
type: custom:grid-layout
layout:
  grid-gap: var(--custom-layout-card-padding)
  grid-template-columns: repeat(2, 1fr) 40%
  grid-template-rows: auto
  grid-template-areas: |
    "top    top     top"
    "lights climate cameras"
    "lights media   presence"
  mediaquery:
    '(max-width: 800px)':
      grid-gap: calc(var(--custom-layout-card-padding) * 1.5)
      grid-template-columns: 0 1fr 0
      grid-template-rows: auto
      grid-template-areas: |
        ". top      ."
        ". lights   ."
        ". climate  ."
        ". media    ."
        ". cameras  ."
        ". presence ."
cards:
  - type: horizontal-stack
    view_layout:
      grid-area: top
    cards:
      - type: custom:button-card
        template: edge
      - type: custom:button-card
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace-minimalist/main
      - type: custom:button-card
        template: chip_icon_state
        variables:
          ulm_chip_icon_state_icon: '🌡️'
          ulm_chip_icon_state_entity: sensor.corridor_temperature
      - type: custom:button-card
        template: edge
  - type: vertical-stack
    view_layout:
      grid-area: lights
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Lights
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light
            entity: light.kitchen_1
          - type: custom:button-card
            template: card_light
            entity: light.kitchen_2
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light_slider_collapse_color
            entity: light.kitchen_leds
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light
            entity: light.dining_room_1
          - type: custom:button-card
            template: card_light
            entity: light.dining_room_2
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light
            entity: light.living_room
          - type: custom:button-card
            template: card_light_slider_collapse_color
            entity: light.living_lamp
  - type: vertical-stack
    view_layout:
      grid-area: climate
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Air Conditioner
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: custom_card_tpx01_aircondition_with_buttons
            variables:
              entity: climate.comedor
              name: A/C Livingroom
          - type: custom:button-card
            template: edge
  - type: vertical-stack
    view_layout:
      grid-area: media
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Media
          - type: custom:button-card
            template: edge
      - type: custom:button-card
        template: card_media_player_with_controls
        variables:
          ulm_card_media_player_with_controls_name: Sonos Kitchen
          ulm_card_media_player_with_controls_entity: media_player.cocina
      - type: custom:button-card
        template: card_media_player_with_control
        entity: media_player.living_tv
        name: TV
      - type: custom:button-card
        template: card_media_player_with_controls
        variables:
          ulm_card_media_player_with_controls_name: Nvidia Shield
          ulm_card_media_player_with_controls_entity: media_player.nvidia_shield
  - type: vertical-stack
    view_layout:
      grid-area: cameras
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Cameras
          - type: custom:button-card
            template: edge
      - type: picture-entity
        entity: camera.street
  - type: vertical-stack
    view_layout:
      grid-area: presence
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Presence
          - type: custom:button-card
            template: edge
      - type: entity-filter
        entities:
          - entity: person.pablo
          - entity: person.natalia
          - entity: person.dad
          - entity: person.housemaid
        state_filter:
          - "home"
        card:
          type: glance
