---
title: Office
path: office
icon: mdi:desktop-mac
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        template: edge
      - type: custom:button-card
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace-minimalist/main
      - type: custom:button-card
        template: chip_icon_state
        variables:
          ulm_chip_icon_state_icon: '🌡️'
          ulm_chip_icon_state_entity: sensor.office_sensor_temperature
      - type: custom:button-card
        template: chip_icon_state
        variables:
          ulm_chip_icon_state_icon: '💧'
          ulm_chip_icon_state_entity: sensor.office_sensor_humidity
      - type: custom:button-card
        template: edge
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Lights
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light
            entity: light.office
          - type: custom:button-card
            template: card_power_outlet
            entity: switch.office_outlet_1
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_light_slider_collapse
            entity: light.office_desk_light
          - type: custom:button-card
            template: card_light_slider_collapse
            entity: light.office_desk_color_light
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Air Conditioner
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: custom_card_tpx01_aircondition_with_buttons
            variables:
              entity: climate.office_thermostat
              name: A/C Office
          - type: custom:button-card
            template: edge
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Media
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: card_media_player_with_controls
            variables:
              ulm_card_media_player_with_controls_name: Sonos Office
              ulm_card_media_player_with_controls_entity: media_player.oficina
          - type: custom:button-card
            template: edge
