---
platform: mqtt
name: sonoff 2
state_topic: "stat/sonoff2/POWER"
command_topic: "cmnd/sonoff2/POWER"
availability_topic: "tele/sonoff2/LWT"
qos: 1
payload_on: "ON"
payload_off: "OFF"
payload_available: "Online"
payload_not_available: "Offline"
retain: false
