---
id: garden_irrigation
alias: 'Garden Irrigation'
trigger:
  - platform: time
    at: '09:00:00'
condition:
  - condition: state
    entity_id: input_boolean.garden_irrigation
    state: 'on'
action:
  - service: script.garden_irrigation
