---
id: motion_detected_backyard
alias: Motion Detected In The Backyard
trigger:
  - platform: state
    entity_id: binary_sensor.ring_jardin_trasero_motion
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'on'
action:
  - service: notify.html5
    data:
      title: 'Security - Backyard'
      message: 'Motion detected in the Backyard'
  - service: homeassistant.turn_on
    entity_id: group.inside_lights
