---
id: letsencrypt_renewal
alias: "Let's Encrypt Renewal"
trigger:
  - platform: time
    at: '00:00:00'
action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
  - service: notify.mobile_app_iphone_de_pablo
    data:
      message: 'The SSL certificate was renewed'
      title: 'SSL certificate renewal'
