---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Argentina/Mendoza
  # Customization file
  customize: !include customize.yaml

  # Load packages
  packages: !include_dir_named configuration

scene:
  - name: Livingroom normal
    entities:
      light.living_lamp:
        state: 'off'
        transition: 5
      light.living_room:
        state: 'on'
  - name: Livingroom movies
    entities:
      light.living_lamp:
        state: 'on'
        transition: 5
        brightness_pct: 60
      light.living_room:
        state: 'off'
