---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Argentina/Mendoza
  # URL for Home Assistant
  external_url: https://ha.pgc.ar:8123
  internal_url: https://ha.pgc.ar:8123
  # Customization file
  customize: !include customize.yaml

  # Load packages
  packages: !include_dir_named integrations

scene: !include_dir_list scenes
