---
id: disable_bedtime_workday
alias: Disable Bed Time Workday
trigger:
  - platform: time
    at: '09:00:00'
condition:
  condition: state
  entity_id: 'binary_sensor.workday_sensor'
  state: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedtime
