---
id: disable_bedtime_weekend
alias: Disable Bed Time Weekend
trigger:
  - platform: time
    at: '10:30:00'
condition:
  condition: state
  entity_id: 'binary_sensor.workday_sensor'
  state: 'off'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedtime
