---
id: disable_bedtime_switch
alias: Disable Bed Time
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.bedroom_switch
      click_type: double
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedtime
