---
id: enable_bedtime
alias: Enable Bed Time
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.bedroom_switch
      click_type: single
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.bedtime
