---
id: toggle_bedtime
alias: Toggle Bed Time Mode
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.bedroom_switch
      click_type: double
action:
  - service: input_boolean.toggle
    data:
      entity_id: input_boolean.bedtime
