---
title: Bedroom
icon: mdi:hotel
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.esphome_bedroom_temperature
        line_color: red
        line_width: 5
        font_size: 75
        animate: true
      - type: custom:mini-graph-card
        entities:
          - sensor.esphome_bedroom_humidity
        line_color: blue
        line_width: 5
        font_size: 75
        animate: true
  - type: glance
    title: Outlets
    entities:
      - entity: switch.bedroom_outlet
        icon: mdi:power-socket-au
        tap_action:
          action: toggle
      - entity: light.bedroom_lamp
        icon: mdi:lamp
        tap_action:
          action: toggle
  - type: custom:mini-media-player
    entity: media_player.fire_tv_bedroom
