---
title: Devices Health
icon: mdi:gauge
cards:
  - type: glance
    title: Door and Window Sensors
    entities:
      - binary_sensor.office_door
      - binary_sensor.stair_window_1
      - binary_sensor.stair_window_2
  - type: entities
    title: Motion Sensors
    entities:
      - binary_sensor.ring_puerta_principal_motion
      - binary_sensor.ring_jardin_trasero_motion
      - binary_sensor.ring_balcon_oficina_motion
      - binary_sensor.ring_techo_comedor_motion
      - binary_sensor.ring_comedor_motion
      - binary_sensor.motion_sensor_office
  - type: entities
    show_header_toggle: false
    name: Ring Cameras - Battery Status
    entities:
      - sensor.ring_puerta_principal_battery
      - sensor.ring_jardin_trasero_battery
      - sensor.ring_balcon_oficina_battery
      - sensor.ring_techo_comedor_battery
      - sensor.ring_comedor_battery
  - type: entities
    show_header_toggle: false
    name: Ring Cameras - Signal Status
    entities:
      - sensor.ring_puerta_principal_wifi_signal_category
      - sensor.ring_jardin_trasero_wifi_signal_category
      - sensor.ring_balcon_oficina_wifi_signal_category
      - sensor.ring_techo_comedor_wifi_signal_category
      - sensor.ring_comedor_wifi_signal_category
