---
title: Devices Health
icon: mdi:gauge
cards:
  - type: entities
    title: Ring Cameras - Battery Status
    show_header_toggle: false
    entities:
      - sensor.ring_puerta_principal_battery
      - sensor.ring_jardin_trasero_battery
      - sensor.ring_balcon_oficina_battery
      - sensor.ring_techo_comedor_battery
      - sensor.ring_comedor_battery
  - type: entities
    title: Ring Cameras - Signal Status
    show_header_toggle: false
    entities:
      - sensor.ring_puerta_principal_wifi_signal_category
      - sensor.ring_jardin_trasero_wifi_signal_category
      - sensor.ring_balcon_oficina_wifi_signal_category
      - sensor.ring_techo_comedor_wifi_signal_category
      - sensor.ring_comedor_wifi_signal_category
  - type: entities
    title: Xiaomi Devices - Battery Status
    show_header_toggle: false
    entities:
      - sensor.stair_window_1_battery
      - sensor.stair_window_2_battery
      - sensor.office_door_battery
      - sensor.office_motion_battery
      - sensor.bedroom_switch_battery
