---
title: Devices Health
icon: mdi:gauge
cards:
  - type: entities
    title: Ring Cameras - Battery Status
    show_header_toggle: false
    entities:
      - sensor.puerta_principal_battery
      - sensor.jardin_trasero_battery
      - sensor.balcon_oficina_battery
      - sensor.techo_comedor_battery
      - sensor.comedor_battery
  - type: entities
    title: Xiaomi Devices - Battery Status
    show_header_toggle: false
    entities:
      - sensor.stair_window_1_battery
      - sensor.stair_window_2_battery
      - sensor.office_door_battery
      - sensor.office_motion_battery
      - sensor.bedroom_switch_battery
