---
title: Devices Health
icon: mdi:gauge
cards:
  - type: entities
    show_header_toggle: false
    name: Ring Cameras - Battery Status
    entities:
      - sensor.ring_puerta_principal_battery
      - sensor.ring_jardin_trasero_battery
      - sensor.ring_balcon_oficina_battery
      - sensor.ring_techo_comedor_battery
      - sensor.ring_comedor_battery
  - type: entities
    show_header_toggle: false
    name: Ring Cameras - Signal Status
    entities:
      - sensor.ring_puerta_principal_wifi_signal_category
      - sensor.ring_jardin_trasero_wifi_signal_category
      - sensor.ring_balcon_oficina_wifi_signal_category
      - sensor.ring_techo_comedor_wifi_signal_category
      - sensor.ring_comedor_wifi_signal_category
  - type: entities
    show_header_toggle: false
    name: Sensors
    entities:
      - binary_sensor.door_window_sensor_158d0002766823
      - binary_sensor.motion_sensor_158d0002239c13
      - binary_sensor.ring_puerta_principal_motion
      - binary_sensor.ring_jardin_trasero_motion
      - binary_sensor.ring_balcon_oficina_motion
      - binary_sensor.ring_techo_comedor_motion
      - binary_sensor.ring_comedor_motion
