---
title: lights
icon: mdi:lightbulb
cards:
  - type: entities
    title: Exterior
    entities:
      - entity: light.balcony
        icon: mdi:lightbulb
        toogle: true
      - entity: light.front_door
        icon: mdi:lightbulb
        toogle: true
  - type: entities
    title: Ground Floor
    show_header_toggle: true
    entities:
      - type: section
        label: Kitchen
      - entity: light.kitchen_1
        icon: mdi:spotlight-beam
        toogle: true
      - entity: light.kitchen_2
        icon: mdi:spotlight-beam
        toogle: true
      - entity: light.kitchen_leds
        icon: mdi:led-strip
        toogle: true
      - type: section
        label: Dining Room
      - entity: light.dining_room_1
        icon: mdi:ceiling-light
        toogle: true
      - entity: light.dining_room_2
        icon: mdi:spotlight-beam
        toogle: true
      - type: section
        label: Living Room
      - entity: light.living_room
        icon: mdi:spotlight-beam
        toogle: true
      - entity: light.living_lamp
        icon: mdi:lamp
        toogle: true
      - type: section
        label: Bedroom
      - entity: light.bedroom_lamp
        icon: mdi:lamp
        toogle: true
      - entity: switch.bedroom_outlet
        icon: mdi:power-socket-au
        toggle: true
      - type: section
        label: Backyard
      - entity: light.backyard
        icon: mdi:lightbulb
        toogle: true
  - type: entities
    title: Top Floor
    show_header_toggle: true
    entities:
      - type: section
        label: Office
      - entity: light.office
        icon: mdi:ceiling-light
        toggle: true
      - entity: light.office_desk_light
        icon: mdi:led-strip
        toggle: true
      - entity: light.office_desk_color_light
        icon: mdi:led-strip
        toggle: true
