---
title: lights
icon: mdi:lightbulb
cards:
  - type: glance
    title: Exterior Lights
    entities:
      - entity: light.balcony
        icon: mdi:lightbulb
        tap_action:
          action: toggle
      - entity: light.front_door
        icon: mdi:lightbulb
        tap_action:
          action: toggle
  - type: glance
    title: Interior Lights
    columns: 4
    entities:
      - entity: light.dinning_room_1
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.dinning_room_2
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.kitchen_1
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.kitchen_2
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_room
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_lamp
        icon: mdi:lamp
        tap_action:
          action: toggle
      - entity: light.office
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.office_desk_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
      - entity: light.office_desk_color_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
  - type: glance
    title: Outlets
    entities:
      - entity: switch.bedroom_outlet
        icon: mdi:power-socket-au
        tap_action:
          action: toggle
      - entity: switch.sonoff_2
        icon: mdi:power-socket-au
        tap_action:
          action: toggle
