---
title: living
icon: mdi:television-classic
cards:
  - type: entities
    title: Lights
    show_header_toggle: true
    entities:
      - type: section
        label: Kitchen
      - entity: light.kitchen_1
        toogle: true
      - entity: light.kitchen_2
        toogle: true
      - type: section
        label: Dinning Room
      - entity: light.dinning_room_1
        toogle: true
      - entity: light.dinning_room_2
        toogle: true
      - type: section
        label: Living Room
      - entity: light.living_room
        toogle: true
      - entity: light.living_lamp
        toogle: true
  - type: thermostat
    entity: climate.comedor
  - type: media-control
    entity: media_player.fire_tv_living
