---
title: living
icon: mdi:television-classic
cards:
  - type: glance
    title: Lights
    entities:
      - entity: light.dinning_room_1
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.dinning_room_2
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_room
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_lamp
        icon: mdi:lamp
        tap_action:
          action: toggle
  - type: thermostat
    entity: climate.comedor
  - type: media-control
    entity: media_player.fire_tv_living
