---
title: living
icon: mdi:television-classic
cards:
  - type: entities
    title: Lights
    show_header_toggle: true
    entities:
      - type: section
        label: Kitchen
      - entity: light.kitchen_1
        icon: mdi:spotlight-beam
        toogle: true
      - entity: light.kitchen_2
        icon: mdi:spotlight-beam
        toogle: true
      - type: section
        label: Dinning Room
      - entity: light.dinning_room_1
        icon: mdi:ceiling-light
        toogle: true
      - entity: light.dinning_room_2
        icon: mdi:spotlight-beam
        toogle: true
      - type: section
        label: Living Room
      - entity: light.living_room
        icon: mdi:spotlight-beam
        toogle: true
      - entity: light.living_lamp
        icon: mdi:lamp
        toogle: true
  - type: custom:simple-thermostat
    entity: climate.comedor
    decimals: 0
    step_size: 1
    modes:
      auto:
        name: false
      cool:
        name: false
      dry:
        name: false
      fan_only:
        name: false
      heat:
        name: false
      'off':
        name: false
  - type: media-control
    entity: media_player.fire_tv_living
