---
title: Main
icon: mdi:home
cards:
  - type: entity-filter
    entities:
      - entity: person.pablo
      - entity: person.natalia
      - entity: person.dad
      - entity: person.housemaid
    state_filter:
      - "home"
    card:
      type: glance
      title: Presence
  - type: alarm-panel
    entity: alarm_control_panel.home_alarm
  - type: entities
    title: Home Modes
    show_header_toggle: false
    entities:
      - entity: input_boolean.auto_cooling
      - entity: input_boolean.auto_heating
      - entity: input_boolean.auto_mosquito_repellent
      - entity: input_boolean.movies
      - entity: input_boolean.vacation
  - type: entity-filter
    entities:
      - entity: light.backyard
        icon: mdi:lightbulb
        tap_action:
          action: toggle
      - entity: light.balcony
        icon: mdi:lightbulb
        tap_action:
          action: toggle
      - entity: light.front_door
        icon: mdi:lightbulb
        tap_action:
          action: toggle
      - entity: light.dining_room_1
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.dining_room_2
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.kitchen_1
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.kitchen_2
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_room
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_lamp
        icon: mdi:lamp
        tap_action:
          action: toggle
      - entity: light.bedroom_lamp
        icon: mdi:lamp
        tap_action:
          action: toggle
      - entity: light.office
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.office_desk_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
      - entity: light.office_desk_color_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
    show_empty: false
    state_filter:
      - "on"
    card:
      type: glance
      title: Lights currently on
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.shellyem1_watts
        line_color: green
        line_width: 5
        font_size: 75
        animate: true
      - type: custom:mini-graph-card
        entities:
          - sensor.monthly_energy
        line_color: green
        line_width: 5
        font_size: 75
        animate: true
  - type: horizontal-stack
    cards:
      - type: sensor
        name: Latency
        entity: sensor.speedtest_ping
      - type: sensor
        name: Download
        entity: sensor.speedtest_download
      - type: sensor
        name: Upload
        entity: sensor.speedtest_upload
  - type: picture-entity
    entity: camera.street
