---
title: main
icon: mdi:home
cards:
  - type: glance
    title: Presence
    entities:
      - person.pablo
      - person.dad
      - person.mom
      - person.housemaid
  - type: entities
    title: Home Modes
    show_header_toggle: false
    entities:
      - entity: input_boolean.away
      - entity: input_boolean.bedtime
      - entity: input_boolean.vacation
  - type: weather-forecast
    entity: weather.dark_sky
  - type: entity-filter
    entities:
      - entity: light.balcony
        icon: mdi:lightbulb
        tap_action:
          action: toggle
      - entity: light.front_door
        icon: mdi:lightbulb
        tap_action:
          action: toggle
      - entity: light.dinning_room_1
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.dinning_room_2
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.kitchen_1
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.kitchen_2
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_room
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.living_lamp
        icon: mdi:lamp
        tap_action:
          action: toggle
      - entity: light.bedroom_lamp
        icon: mdi:lamp
        tap_action:
          action: toggle
      - entity: light.office
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.office_desk_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
      - entity: light.office_desk_color_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
    show_empty: false
    state_filter:
      - "on"
    card:
      type: glance
      title: Lights currently on
  - type: horizontal-stack
    cards:
      - type: sensor
        name: Latency
        entity: sensor.speedtest_ping
      - type: sensor
        name: Download
        entity: sensor.speedtest_download
      - type: sensor
        name: Upload
        entity: sensor.speedtest_upload
  - type: picture-entity
    entity: camera.street
