---
title: Media
icon: mdi:youtube-tv
cards:
  - type: media-control
    entity: media_player.fire_tv_bedroom
  - type: media-control
    entity: media_player.fire_tv_living
  - type: media-control
    entity: media_player.comedor
  - type: media-control
    entity: media_player.oficina
