---
title: Media
icon: mdi:youtube-tv
cards:
  - type: custom:mini-media-player
    entity: media_player.fire_tv_living
  - type: custom:mini-media-player
    entity: media_player.kitchen
  - type: custom:mini-media-player
    entity: media_player.oficina
