---
title: office
icon: mdi:tie
cards:
  - type: glance
    title: Lights
    entities:
      - entity: light.office
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.office_desk_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
      - entity: light.office_desk_color_light
        icon: mdi:led-strip
        tap_action:
          action: toggle
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.office_temperature
        line_color: red
        line_width: 5
        font_size: 75
        animate: true
      - type: custom:mini-graph-card
        entities:
          - sensor.office_humidity
        line_color: blue
        line_width: 5
        font_size: 75
        animate: true
  - type: thermostat
    entity: climate.office_thermostat
  - type: media-control
    entity: media_player.oficina
