---
title: Security
icon: mdi:shield-home
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.street
          - type: picture-entity
            entity: camera.puerta_principal
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.balcon_oficina
          - type: picture-entity
            entity: camera.techo_comedor
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.jardin_trasero
          - type: picture-entity
            entity: camera.comedor
  - type: entities
    title: Door and Window Sensors
    show_header_toggle: false
    entities:
      - binary_sensor.office_door
      - binary_sensor.stair_window_1
      - binary_sensor.stair_window_2
  - type: entities
    title: Motion Sensors
    show_header_toggle: false
    entities:
      - binary_sensor.puerta_principal_motion
      - binary_sensor.jardin_trasero_motion
      - binary_sensor.balcon_oficina_motion
      - binary_sensor.techo_comedor_motion
      - binary_sensor.comedor_motion
      - binary_sensor.office_motion
