---
include_domains:
  - alarm_control_panel
  - camera
  - climate
  - light
exclude_entities:
  - light.dinning_room_1
  - light.dinning_room_2
  - light.kitchen_1
  - light.kitchen_2
  - light.gateway_light_7c49eb192d55
