---
id: toggle_movies
alias: Toggle movies mode
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: 'Movies'
action:
  - service: input_boolean.toggle
    data:
      entity_id: input_boolean.movies
