---
id: alarm_armed_away
alias: Alarm armed away
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'ALARM - Armed'
      message: "{{ states('sensor.date_time') }} - Alarm armed in Away mode"
