---
id: alarm_disarmed
alias: Alarm disarmed
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'disarmed'
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'ALARM - Disarmed'
      message: "{{ states('sensor.time') }} - The alarm is Disarmed"
