---
id: alarm_armed_home
alias: Alarm armed home
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'ALARM - Armed'
      message: "{{ states('sensor.time') }} - Alarm armed in Home mode"
  - service: tts.google_translate_say
    data:
      entity_id: media_player.bedroom
      message: "The alarm has been armed. Good night!"
