---
id: alarm_arm_away
alias: Alarm Arm Away
trigger:
  - platform: template
    value_template: "{{states('person.pablo') != 'home'}}"
  - platform: template
    value_template: "{{states('person.dad') != 'home'}}"
  - platform: template
    value_template: "{{states('person.housemaid') != 'home'}}"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{states('person.pablo') != 'home'}}"
    - condition: template
      value_template: "{{states('person.dad') != 'home'}}"
    - condition: template
      value_template: "{{states('person.housemaid') != 'home'}}"
action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.home_alarm
