---
id: alarm_arm_away
alias: Alarm Arm Away
trigger:
  - platform: state
    entity_id: group.presence
    from: home
    to: away
action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.home_alarm
