---
id: alarm_arm_away
alias: Alarm Arm Away
trigger:
  - platform: template
    value_template: "{{states('group.presence') != 'home'}}"
action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.home_alarm
