---
id: alarm_arm_home_on_bedtime
alias: 'Arm alarm in Home mode on bedtime'
trigger:
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
action:
  - service: alarm_control_panel.alarm_arm_home
    data:
      entity_id: alarm_control_panel.home_alarm
