---
id: alarm_arm_home
alias: 'Arm alarm in Home mode'
trigger:
  - device_id: 6ca70a5a3d435609413cf57bd7e87be5
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
action:
  - service: alarm_control_panel.alarm_arm_home
    data:
      entity_id: alarm_control_panel.home_alarm
