---
id: alarm_disarm_home_weekend
alias: Alarm Disarm Home Weekend
trigger:
  - platform: time
    at: '10:30:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.home_alarm
