---
id: alarm_disarm_away
alias: Alarm Disable Away
trigger:
  - platform: state
    entity_id: group.presence
    from: away
    to: home
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.home_alarm
