---
id: alarm_disarm_away
alias: Alarm Disable Away
trigger:
  - platform: state
    entity_id: person.pablo
    to: home
  - platform: state
    entity_id: person.dad
    to: home
  - platform: state
    entity_id: person.housemaid
    to: home
condition:
  condition: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.home_alarm
