---
id: notify_alarm_disarmed
alias: 'Send notification when alarm is Disarmed'
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'disarmed'
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'ALARM - Disarmed'
      message: "The alarm is Disarmed at {{ states('sensor.date_time') }}"
