---
id: notify_alarm_armed_home
alias: 'Send notification when alarm is Armed Home'
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
action:
  - service: notify.mobile_app_iphone_de_pablo
    data:
      title: 'ALARM - Armed'
      message: "The alarm is armed in Home mode {{ states('sensor.date_time') }}"
