---
id: trigger_armed_home
alias: 'Trigger alarm while armed home'
trigger:
  - platform: state
    entity_id: >-
      {{ expand(state_attr('group.exterior_sensors', 'entity_id')) | map(attribute='entity_id') | list }}
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_home
action:
  service: alarm_control_panel.alarm_trigger
  entity_id: alarm_control_panel.home_alarm
