---
id: trigger_armed_away
alias: 'Trigger alarm while armed away'
trigger:
  - platform: state
    entity_id: group.alarm_away_sensors
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
action:
  service: alarm_control_panel.alarm_trigger
  entity_id: alarm_control_panel.home_alarm
